spring:
  application:
    name: Cripto-Rate-Api

  data:
    redis:
      host: redis
      port: 6379


  cache:
    type: redis

  server:
    port: ${PORT:8080}


coingecko:
  base-url: https://api.coingecko.com/api/v3
  api-key: