spring:
  application:
    name: Cripto-Rate-Api

  cache:
    type: simple

coingecko:
  base-url: https://api.coingecko.com/api/v3
  api-key: ${COINGECKO_API_KEY}

server:
  port: ${PORT:8080}

  logging:
    level:
      org.springframework.web: DEBUG
      org.springdoc: DEBUG
      com.fasterxml.jackson: DEBUG